language: python

python: '3.7'

install:
  - "pip install pytest"
  - "pip install -e ."

script:
  - pytest

deploy:
  provider: pypi
  user: maxhumber
  password: $PYPI_PASSWORD
  on:
    tags: true
